"""
Canonical football team name mappings.
"""

CANONICAL_MAP = {
    "arsenal": "Arsenal",
    "aston villa": "Aston Villa",
    "bournemouth": "Bournemouth",
    "brentford": "Brentford",
    "brighton": "Brighton & Hove Albion",
    "burnley": "Burnley",
    "chelsea": "Chelsea",
    "crystal palace": "Crystal Palace",
    "everton": "Everton",
    "fulham": "Fulham",
    "liverpool": "Liverpool",
    "man city": "Manchester City",
    "man utd": "Manchester United",
    "mancity": "Manchester City",
    "manchester city": "Manchester City",
    "manchester united": "Manchester United",
    "newcastle": "Newcastle United",
    "newcastle united": "Newcastle United",
    "nottingham forest": "Nottingham Forest",
    "forest": "Nottingham Forest",
    "sheffield united": "Sheffield United",
    "southampton": "Southampton",
    "tottenham": "Tottenham Hotspur",
    "tottenham hotspur": "Tottenham Hotspur",
    "west ham": "West Ham United",
    "wolves": "Wolverhampton Wanderers",
    "watford": "Watford",
    "aberdeen": "Aberdeen",
    "celtic": "Celtic",
    "dundee": "Dundee",
    "dundee united": "Dundee United",
    "hearts": "Hearts",
    "hibernian": "Hibernian",
    "hibs": "Hibernian",
    "kilmarnock": "Kilmarnock",
    "motherwell": "Motherwell",
    "rangers": "Rangers",
    "st johnstone": "St Johnstone",
    "st mirren": "St Mirren",
    "atletico madrid": "Atletico Madrid",
    "barcelona": "Barcelona",
    "bayern munich": "Bayern Munich",
    "juventus": "Juventus",
    "paris saint-germain": "Paris Saint-Germain",
    "psg": "Paris Saint-Germain",
    "real madrid": "Real Madrid",
    "england": "England",
    "scotland": "Scotland",
    "france": "France",
    "germany": "Germany",
    "spain": "Spain",
    "italy": "Italy",
    "netherlands": "Netherlands",
    "belgium": "Belgium",
    "portugal": "Portugal",
    "brazil": "Brazil",
    "argentina": "Argentina",
    "uruguay": "Uruguay",
    "colombia": "Colombia",
    "chile": "Chile",
    "mexico": "Mexico",
    "usa": "United States",
    "united states": "United States",
    "canada": "Canada",
    "japan": "Japan",
    "south korea": "South Korea",
    "north korea": "North Korea",
    "australia": "Australia",
    "new zealand": "New Zealand",
    "south africa": "South Africa",
    "nigeria": "Nigeria",
    "ghana": "Ghana",
    "senegal": "Senegal",
    "morocco": "Morocco",
    "tunisia": "Tunisia",
    "algeria": "Algeria",
    "egypt": "Egypt",
    "cameroon": "Cameroon",
    "ivory coast": "Ivory Coast",
    "hong kong": "Hong Kong",
    "india": "India",
    "indonesia": "Indonesia",
    "kenya": "Kenya",
    "hungary": "Hungary",
    "costa rica": "Costa Rica",
    "panama": "Panama",
    "jamaica": "Jamaica",
    "haiti": "Haiti",
    "ipswich town": "Ipswich Town",
    "leeds united": "Leeds United",
    "middlesbrough": "Middlesbrough",
    "sunderland": "Sunderland",
    "coventry city": "Coventry City",
    "charlton athletic": "Charlton Athletic",
    "accrington stanley": "Accrington Stanley",
    "morecambe": "Morecambe",
    "plymouth argyle": "Plymouth Argyle",
    "ross county": "Ross County",
    "bay fc": "Bay FC",
    "dallas trinity fc": "Dallas Trinity FC",
    "fc goa": "FC Goa",
    "denver summit fc": "Denver Summit FC",
    "young boys": "Young Boys",
    "gotham fc": "Gotham FC",
    "portland thorns": "Portland Thorns",
    "eintracht frankfurt": "Eintracht Frankfurt",
    "galatasaray": "Galatasaray",
    "psv": "PSV",
    "zenit": "Zenit",
    "athletic bilbao": "Athletic Bilbao",
    "osasuna": "Osasuna",
    "levante": "Levante",
    "legia warsaw": "Legia Warsaw",
    "ac milan": "AC Milan",
}

LEGITIMATE_TEAMS = set(CANONICAL_MAP.values())
